#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

# source example 
#. /home/rokot/OpenFOAM/OpenFOAM-v2412/etc/bashrc

. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------


keepCases="
common
"

loseCases="
SpalartAllmaras
LaunderSharmaKE
kOmegaSST
kEpsilonPhitF
"


for caseName in $loseCases
do
    removeCase "$caseName"
done


rm -r Figures
rm support_Files/log.post



#------------------------------------------------------------------------------
