#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

# source example 
#. /home/rokot/OpenFOAM/OpenFOAM-v2412/etc/bashrc

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

#~/miniconda3/bin/conda init
#wait
#conda activate OFpy

selectModel()
{
    sed -i "s/modelName/$1/" "$1/constant/turbulenceProperties"
}

reduceTolerance()
{
    sed -i "s/relTol          0.1;/relTol          0.01;/" "$1/system/fvSolution"
}

decreaseRelaxation()
{
    sed -i 's/".*"            0.9/".*"            0.65/' "$1/system/fvSolution"
}

isoValue()
{
    sed -i "s/isoValue  0;/isoValue  1e-10;/" "$1/system/interface"
}

cases=" LaunderSharmaKE kEpsilonPhitF SpalartAllmaras kOmegaSST"

mkdir Figures
for modelName in $cases; do
        cloneCase common "$modelName"
    case "$modelName" in
    LaunderSharmaKE)
       # decreaseRelaxation "$cases"
        reduceTolerance "$modelName"
	isoValue "$modelName"
        ;;

    kEpsilonPhitF)
        reduceTolerance "$modelName"
        ;;

    SpalartAllmaras)
        decreaseRelaxation "$modelName"
        ;;
    esac
    selectModel $modelName
    echo "Entering $modelName..."
    cd "$modelName" || { echo "Failed to enter $case"; continue; }
    cp ../common/Diffuser.msh .
    # === Place your commands here ===
    # For example:
    cp -r 0.orig 0
    wait
    fluentMeshToFoam  Diffuser.msh > log.fluent 2>&1  &
    wait
    checkMesh >log.mesh &
    wait
    simpleFoam >log.solver &
    wait
   # cp -r postProcessing ../Simulations/results/$case/

    cd ..
done

cd support_Files
python PostProcessing.py > log.post 2>&1 &



#------------------------------------------------------------------------------
